{"name": "test_vwo_login_negative", "status": "broken", "statusDetails": {"message": "RecursionError: maximum recursion depth exceeded", "trace": "setup = <selenium.webdriver.chrome.webdriver.WebDriver (session=\"1da0ce41ad3f612f0a2654c9c841b17e\")>\n\n    @allure.epic(\"VWO login\")\n    @pytest.mark.negative\n    def test_vwo_login_negative(setup):\n        driver = setup\n        loginpage = LoginPage(driver)\n        loginpage.login_to_vwo(usr=\"admin@gmail.com\", pwd=\"admin\")\n        time.sleep(20)\n>       error_message = loginpage.get_error_message_text()\n\ntests\\vwoLoginTests\\test_vwo_login.py:25: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\ntests\\pageObjects\\loginPage.py:59: in get_error_message_text\n    self.get_error_message_text()\ntests\\pageObjects\\loginPage.py:59: in get_error_message_text\n    self.get_error_message_text()\nE   RecursionError: maximum recursion depth exceeded\n!!! Recursion detected (same locals & position)"}, "start": 1715949344851, "stop": 1715949365489, "uuid": "cc5e09e4-5e51-40c8-94ce-d2a15209cf51", "historyId": "d768d3d769f5652f534d483ce8b8f9ed", "testCaseId": "d768d3d769f5652f534d483ce8b8f9ed", "fullName": "tests.vwoLoginTests.test_vwo_login#test_vwo_login_negative", "labels": [{"name": "epic", "value": "VWO login"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests.vwoLoginTests"}, {"name": "suite", "value": "test_vwo_login"}, {"name": "host", "value": "DESKTOP-K766CG4"}, {"name": "thread", "value": "17092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.vwoLoginTests.test_vwo_login"}]}